### ISSUE TITLE
Localization support?

### ISSUE THREAD

**Issue by rizkysyazuli** [Eworm/big-kahuna#32]
I don't see any localization/translation option when creating menus. Switching locales also doesn't have any effect on the frontend. It only show the default language.

Is it supported? Any plans for this? Pls forgive me in advanced if i missed it.

Thx.

**Comment by Eworm** [comment]
There's a Statamic user testing a localized version right now, and I haven't heard from him in a while, so I think there aren't any bugs. I'll merge that branch with the master so BK will support localization.

**Comment by Eworm** [comment]
Done! The new version on the marketplace support localization.

**Comment by rizkysyazuli** [comment]
Sweet! Looks promising 👍 But still a few bugs though. I hope it's okay if i post it here.

So i have two locales: Indonesian as the default, and English as second.

1. If a page name is not localized, the menu returns empty string when i switched to English. Not ideal, because some page names are intentionally not translated.
<img width="365" alt="Tangkapan layar 2019-10-25 23 49 35" src="https://user-images.githubusercontent.com/152221/67589405-963e8680-f782-11e9-9440-e4a52ff74468.png">

2. Home page title returns empty even though the English translation is available.
<img width="397" alt="Tangkapan layar 2019-10-25 23 44 52" src="https://user-images.githubusercontent.com/152221/67589684-3b595f00-f783-11e9-84da-125e1171d53e.png">

3. In the menu editor, dragging newly added menu items will show `undefined` in the title label.
4. In the menu editor, dragging existing menu item will show `null` in the title label.
5. I still don't see an option to translate custom links.

_i can't take a screenshot for 3 & 4 while at the same time interacting with the menu editor_. sorry.

**Comment by Eworm** [comment]
Thanks for the feedback! I have some questions for you:

1. Is one of the localized titles empty? Would adding the same text to both titles solve this?
2. How did you add the home link?

I've solved 3 & 4, and you're right, there isn't an option for translating custom links yet.

**Comment by rizkysyazuli** [comment]
Hmm, this is weird.

1. I've added a `title` in the en.index.md file. But it still shows blank. So that's not the problem.
2. The home page comes from the default Statamic installation. But i've wired it to a custom fieldset though.

I can't seem to figure out a pattern though. The difference between pages that has empty title and the rest is not clear 😵 But it's late here. I might be wrong 💤 i'll have another look in the morning.

Not sure if it matters. But i'm running Statamic under Valet+ with nginx and PHP 7.2

**Comment by rizkysyazuli** [comment]
Anyway.. the only pattern i see is that the links that has working translation are the ones that already has translations before i install BigKahuna.

But that doesn't seem logical to me. and that's just an assumption.

I also tried deploying this to my staging in case localization is not working in my local env (which happens before). But same thing happens.

So, if you need me to send you anything. Logs, yaml files, etc. Just let me know.

---

Here's a preview of the empty text link happening even though the English translation is present.

Indonesian locale:

<img width="924" alt="Jepretan Layar 2019-10-29 pukul 16 50 19" src="https://user-images.githubusercontent.com/152221/67756334-64703d00-fa6c-11e9-9eec-864283e47296.png">

English locale:

<img width="915" alt="Jepretan Layar 2019-10-29 pukul 16 50 42" src="https://user-images.githubusercontent.com/152221/67756366-7651e000-fa6c-11e9-942c-87c15cedc393.png">

Result:

<img width="433" alt="Jepretan Layar 2019-10-29 pukul 16 55 13" src="https://user-images.githubusercontent.com/152221/67756721-190a5e80-fa6d-11e9-8d25-5b495e9b1b4b.png">

**Comment by Eworm** [comment]
I've decided on a new (and better) approach. In the new setup you can make a menu for each locale. This makes it a lot easier to customize the menu, and really make different menus for each locale. It also keeps the UI simple.

**Comment by rizkysyazuli** [comment]
more control seems like a good idea. but at the same time, maintaining multiple menus doesn't seem fun to me 🤣

**Comment by Eworm** [comment]
:-)

**Comment by Eworm** [comment]
I published a new release with localization options! Let me know if you find any bugs.

**Comment by rizkysyazuli** [comment]
Hey.. so, i got this error on the "Menus" screen after upgrading. I have to delete the old `navigation.json` file to clear the error. It seems the upgrade doesn't play well with existing menus.

```
ErrorException in BigKahunaController.php line 37:
Undefined index: locale
```

Anyway, once that's out of the way. It is indeed working as expected now. There's still one annoyance though.. Untranslated menu items is not searchable in the menu editor when in secondary locale.

**Comment by Eworm** [comment]
That's correct, the setup is different, so it doesn't work with the old setup. I may add a note.

**Comment by rizkysyazuli** [comment]
one more thing.. the root UL `class` name is repeated in the submenus. the expected output is child ULs should use the provided `submenu_class` param.

---

<img width="403" alt="Tangkapan layar 2019-11-06 16 19 06" src="https://user-images.githubusercontent.com/152221/68285070-2c42ad00-00b1-11ea-8b84-85dc0493622d.png">

---

```
{{ big_kahuna
    menu="navigation-id"
    class="navbar-nav"
    active_class="active"
    item_class="nav-item"
    parent_class="dropdown"
    submenu_class="dropdown-menu"
    submenu_item_class="dropdown-item"
}}
```
